SYSTEM_PREAMBLE = (
    "You are InnerNets.SurferPlanner. "
    "Return ONLY a single valid JSON object that conforms to the provided schema—no prose."
)

GENERATE_SURFER_INSTRUCTION = (
    "<task>\n"
    "You are planning a long-running web exploration that powers a user-facing feed.\n"
    "Your goal: add meaningful new value to the feed by finding the latest updates and complementary perspectives—\n"
    "not repeating prior items.\n\n"
    "Browser agent behavior (design for this loop):\n"
    "- It will take your instruction and generate search queries.\n"
    "- It will read the top results and also follow salient links inside those pages.\n"
    "- It will use the findings to generate new follow-up queries.\n"
    "- It will iterate this loop 3 times to produce fresh, high-signal curations.\n\n"
    "What you must produce:\n"
    "(1) instruction — a concise multi-sentence paragraph (2–4 sentences) that tells the agent WHAT to search (keywords),\n"
    "    WHERE to look (domains/sources), and WHY (purpose), with guidance that maintains novelty and avoids repeats across iterations.\n"
    "(2) context — a compact, multi-paragraph synthesis of what is already known (from the prior context) and the specific gaps/targets\n"
    "    to pursue next so each iteration trends toward newer information and alternative perspectives.\n"
    "Keep the instruction crisp; let the context carry rich details.\n"
    "</task>\n\n"
    "<mission>\n{{mission}}\n</mission>\n\n"
    "<sources>\n{{sources_text}}\n</sources>\n\n"
    "<prior_context>\n{{prior_context_str}}\n</prior_context>\n\n"
    "Return ONLY JSON: {\n"
    "  \"instruction\": string,\n"
    "  \"context\": string\n"
    "}"
)

REMIX_CURATIONS = (
    "<task>\n"
    "You are remixing multi-iteration Surfer results into a user-facing feed.\n"
    "Produce curations that are engaging to scroll and informative to read.\n"
    "For EACH curation return:\n"
    "- title — a concise, compelling headline.\n"
    "- body_md — multi-paragraph markdown-like content with bolded key phrases and/or short bullet points.\n"
    "             Do NOT include inline links in the body; the URLs are listed separately.\n"
    "- links[] — 1+ URLs chosen ONLY from the provided Surfer curations’ links (never fabricate).\n"
    "Goals: connect dots, add perspective, and avoid repeating prior items; prefer freshness and complementary sources.\n"
    "Quantity: as many curations as needed to reflect the material (no fixed cap).\n"
    "</task>\n\n"
    "<mission>\n{{mission}}\n</mission>\n\n"
    "<sources>\n{{sources_text}}\n</sources>\n\n"
    "<prior_context>\n{{prior_context_str}}\n</prior_context>\n\n"
    "<surfer_curations>\n{{raw_curations_json}}\n</surfer_curations>\n\n"
    "Return ONLY JSON: {\n"
    "  \"curations\": [ { \"title\": string, \"body_md\": string, \"links\": [ { \"url\": string, \"title\"?: string } ] } ]\n"
    "}"
)
